# Site version. See: https://semver.org/
#
version: 2.0.0

# General site settings
#
permalink: pretty

# RSS/JSON feed settings. See:
#
#   https://github.com/snaptortoise/jekyll-rss-feeds
#   https://github.com/snaptortoise/jekyll-json-feeds
#
# Also used in some other places now, so check around before changing!
#
name: The Yak Collective
description: The Yak Collective is a network of over 300 independent consultants, coaches, and freelancers with varied technical and creative skills.
url: https://yakcollective.org
feed_items: 255
feed_update_period: daily
feed_update_frequency: 1

# Collections
#
collections:
  members:
    output: true
    order:
      - venkatesh-rao.md
      - paul-millerd.md
      - pamela-hobart.md
      - tom-critchlow.md
      - amanda-reeves.md
      - david-mcdougall.md
      - darren-kong.md
      - vaughn-tan.md
      - randy-lubin.md
      - vlad-mehakovic.md
      - thomas-verhagen.md
      - alex-dobrenko.md
      - sachin-benny.md
      - jordan-peacock.md
      - anne-laure-le-cunff.md
      - vinay-debrou.md
      - benjamin-taylor.md
      - nita-baum.md
      - rodrigo-pinto.md
      - ben-mosior.md
      - harry-pottash.md
      - martha-balaile.md
      - jordan-allen.md
  projects:
    output: true
  sequences:
    output: false

# Per-page defaults
#
defaults:
  - scope:
      path: ""
      type: members
    values:
      layout: member
      permalink: /:collection/:name
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      permalink: /:collection/:name

# Includes and excludes
#
include: 
  - _redirects
exclude:
  - README.md
  - FEEDS.md
  - TODO.md
  - yak-build.sh
  - yak-make-ini.sh
  - yak-make-posts.rb
  - yak-planet.db
  - yak-planet.ini
