# Site version. See: https://semver.org/
#
version: 2.7.0

# Gemfile-based plugins
#
plugins:
  - jekyll-titles-from-headings
  - jekyll-datapage-generator

# RSS/JSON feed settings. See:
#
#   https://github.com/snaptortoise/jekyll-rss-feeds
#   https://github.com/snaptortoise/jekyll-json-feeds
#
# Also used in some other places now, so check around before changing!
#
name: The Yak Collective
description: The Yak Collective is an online space for collaborative tinkering.
url: https://www.yakcollective.org

# Generate member pages from _data/knack_yaks.json
#
#     https://github.com/avillafiorita/jekyll-datapage_gen
#
page_gen:
  - data: knack_yaks.records
    template: page-member
    dir: members
    name: field_101_raw
    title: field_97_raw

# Per-page defaults
#
defaults:
  - scope:
      path: "newsletter/*"
      type: posts
    values:
      layout: post-with-title
  - scope:
      path: "projects/*/*"
      type: pages
    values:
      layout: page-project-page
  - scope:
      path: "projects/*"
      type: pages
    values:
      layout: page-project
  - scope:
      path: "study-groups/*"
      type: pages
    values:
      layout: page-study-group
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# Kramdown parser option
#
kramdown:
  toc_levels: 2..6

# Includes and excludes
#
include:
  - _redirects
exclude:
  - package.json
  - package-lock.json
  - README.md
  - TODO.md
