permalink: pretty
include: 
    - _redirects
exclude:
    - README.md
    - CHANGELOG.md
    - TODO.md
    - yak-build.sh
    - yak-make-ini.rb
    - yak-make-posts.rb
    - yak-planet.db
    - yak-planet.ini
