# Site version. See: https://semver.org/
#
version: 2.3.0

# Default accent color
#
accent_color: "250,175,50"

# General site settings
#
permalink: pretty

# RSS/JSON feed settings. See:
#
#   https://github.com/snaptortoise/jekyll-rss-feeds
#   https://github.com/snaptortoise/jekyll-json-feeds
#
# Also used in some other places now, so check around before changing!
#
name: The Yak Collective
description: The Yak Collective is a network of over 300 independent consultants, coaches, and freelancers with varied technical and creative skills.
url: https://www.yakcollective.org

# Gemfile-based plugins
#
plugins:
  - jekyll-titles-from-headings

# Per-page defaults
#
defaults:
  - scope:
      path: "members/*"
      type: pages
    values:
      layout: page-member
  - scope:
      path: "projects/*/*"
      type: pages
    values:
      layout: page-project-page
  - scope:
      path: "projects/*"
      type: pages
    values:
      layout: page-project
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# Kramdown parser option
#
kramdown:
  toc_levels: 2..6

# Includes and excludes
#
include:
  - _redirects
exclude:
  - bin
  - css/fonts.source.css
  - functions
  - package.json
  - README.md
  - resources
