# Site version. See: https://semver.org/
#
version: 2.2.0

# Default accent color
#
accent_color: "250,175,50"

# General site settings
#
permalink: pretty

# RSS/JSON feed settings. See:
#
#   https://github.com/snaptortoise/jekyll-rss-feeds
#   https://github.com/snaptortoise/jekyll-json-feeds
#
# Also used in some other places now, so check around before changing!
#
name: The Yak Collective
description: The Yak Collective is a network of over 300 independent consultants, coaches, and freelancers with varied technical and creative skills.
url: https://optimistic-jennings-266cab.netlify.app
feed_items: 255
feed_update_period: daily
feed_update_frequency: 1

# Collections
#
collections:
  projects:
    output: true
  project_pages:
    output: true

# Per-page defaults
#
defaults:
  - scope:
      path: "members/"
      type: pages
    values:
      layout: member
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      permalink: /projects/:name/
  - scope:
      path: ""
      type: project_pages
    values:
      layout: project-page
      permalink: /projects/pages/:name/

# Kramdown parser option
#
kramdown:
  toc_levels: 2..6

# Includes and excludes
#
include:
  - _redirects
exclude:
  - assets/static/fonts-src.css
  - assets/static/member-placeholder.jpg
  - assets/static/mkfonts.sh
  - functions
  - package.json
  - README.md
