# Site version. See: https://semver.org/
#
version: 2.0.0

# General site settings
#
permalink: /:categories/:title/

# RSS/JSON feed settings. See:
#
#   https://github.com/snaptortoise/jekyll-rss-feeds
#   https://github.com/snaptortoise/jekyll-json-feeds
#
# Also used in some other places now, so check around before changing!
#
name: The Yak Collective
description: The Yak Collective is a network of over 300 independent consultants, coaches, and freelancers with varied technical and creative skills.
url: https://yakcollective.org
feed_items: 255
feed_update_period: daily
feed_update_frequency: 1

# Includes and excludes
#
include: 
  - _redirects
exclude:
  - README.md
  - CHANGELOG.md
  - TODO.md
  - yak-build.sh
  - yak-make-ini.rb
  - yak-make-posts.rb
  - yak-planet.db
  - yak-planet.ini
