backend:
  name: github
  repo: The-Yak-Collective/yakcollective
  branch: warren-structure
publish_mode: editorial_workflow
media_folder: assets/
site_url: https://yakcollective.org
collections:
  - name: members
    label: Members
    folder: _members/
    create: true
    editor:
      preview: false
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: member
      - label: UID
        name: name
        widget: string
        required: true
      - label: Name
        name: title
        widget: string
        required: true
      - label: Avatar
        name: avatar
        widget: image
        required: true
      - label: Join Date
        name: date
        widget: datetime
        format: YYYY-MM-DD
        dateFormat: true
        timeFormat: false
        pickerUtc:  true
        required: true
      - label: Partner
        name: partner
        widget: boolean
        required: false
      - label: Title
        name: tagline
        widget: string
        required: false
      - label: Indie Status
        name: indie_status
        widget: string
        required: true
      - label: Previously
        name: previously
        widget: string
        required: false
      - label: Twitter
        name: twitter
        widget: string
        required: false
      - label: RSS Feed
        name: feed
        widget: string
        required: false
      - label: Web Links
        name: links
        widget: list
        required: false
        fields:
          - label: Title
            name: title
            widget: string
          - label: URL
            name: url
            widget: string
      - label: About
        name: body
        widget: markdown
        required: false
  - name: projects
    label: Projects
    folder: _projects/
    create: true
    editor:
      preview: false
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: project
      - label: UID
        name: name
        widget: string
        required: true
      - label: Name
        name: title
        widget: string
        required: true
      - label: Tagline
        name: tagline
        widget: string
        required: true
      - label: Is Published?
        name: published
        widget: boolean
        required: false
      - label: Published Date
        name: date
        widget: datetime
        format: YYYY-MM-DD
        dateFormat: true
        timeFormat: false
        pickerUtc: true
        required: false
      - label: Type
        name: type
        widget: select
        options: [ Report ]
        default: [ Report ]
        required: true
      - label: Sequence
        name: sequence
        widget: relation
        collections: sequences
        searchFields: [ title ]
        valueField: name
        displayFields: [ title ]
        required: true
      - label: Hero Image
        name: hero_image
        widget: image
        required: true
      - label: Accent Color
        name: accent_color
        widget: string
        required: true
      - label: Additional CSS
        name: page_css
        widget: text
        required: false
      - label: Summary
        name: summary
        widget: markdown
        required: true
      - label: Project Leads
        name: lead_editors
        widget: relation
        collections: members
        searchFields: [ title ]
        valueField: name
        displayFields: [ title ]
        multiple: true
        required: true
      - label: Collaborators
        name: collaborators
        widget: relation
        collections: members
        searchFields: [ title ]
        valueField: name
        displayFields: [ title ]
        multiple: true
        required: true
      - label: Page Content
        name: body
        widget: markdown
        required: true
  - label: Sequences
    name: sequences
    folder: _sequences/
    create: true
    editor:
      preview: false
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: project-list
      - label: UID
        name: name
        widget: string
        required: true
      - label: Name
        name: title
        widget: string
        required: true
      - label: Start Date
        name: date
        widget: datetime
        format: YYYY-MM-DD
        dateFormat: true
        timeFormat: false
        pickerUtc: true
        required: true
      - label: Counting Phrase
        name: count_phrase
        widget: string
        required: false
      - label: Sequence Description
        name: body
        widget: markdown
        required: false
  - label: Pages
    name: pages
    editor:
      preview: false
    files: 
      - label: Home
        name: home-page
        file: index.md
        fields:
          - label: Layout
            name: layout
            widget: hidden
            default: minimal
          - label: Content
            name: body
            widget: markdown
            required: true
      - label: Projects
        name: projects-page
        file: projects.md
        fields:
          - label: Layout
            name: layout
            widget: hidden
            default: project-list
          - label: Title
            name: title
            widget: string
            required: true
          - label: Content
            name: body
            widget: markdown
            required: true
      - label: Members
        name: members-page
        file: members.md
        fields:
          - label: Layout
            name: layout
            widget: hidden
            default: member-list
          - label: Title
            name: title
            widget: string
            required: true
          - label: Partners Blurb
            name: partners_blurb
            widget: markdown
            required: true
          - label: Collaborators Blurb
            name: collaborators_blurb
            widget: markdown
            required: true
          - label: Content
            name: body
            widget: hidden
            required: false
      - label: About
        name: about-page
        file: about.md
        fields:
          - label: Layout
            name: layout
            widget: hidden
            default: page
          - label: Title
            name: title
            widget: string
            required: true
          - label: Content
            name: body
            widget: markdown
            required: true
