backend:
  name: github
  repo: The-Yak-Collective/yakcollective
  branch: astonishing-stories
  open_authoring: true
publish_mode: editorial_workflow
media_folder: assets/dynamic/
site_url: https://optimistic-jennings-266cab.netlify.app
collections:
  - label: How to Use This Interface # First, so open by default
    name: help
    editor:
      preview: false
    files: 
      - label: Help
        name: help
        file: help.md
        fields:
          - label: Layout
            name: layout
            widget: hidden
            default: minimal
          - label: Content
            name: body
            widget: markdown
            required: true
  - name: members
    label: Members
    folder: _members/
    create: true
    editor:
      preview: true
    sortableFields: ["name", "date"]
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: member
      - label: UID
        name: name
        widget: string
        required: true
        hint: Internal identifier. Must be composed only of lower-case ASCII letters and dashes. Normally you will use your (romanized) name here, with spaces replaced by dashes, family name first (so, "Jamie Smith" would be "smith-jamie").
        pattern: [ "[a-z-]+", "Must be composed only of lower-case ASCII letters and dashes" ]
      - label: Name
        name: title
        widget: string
        required: true
      - label: Avatar
        name: avatar
        widget: image
        required: true
        hint: Must be a square image in JPEG format. Please name using your UID. To prevent blurry-ness, you should use an image at least 64 pixels on a side.
      - label: Join Date
        name: date
        widget: datetime
        format: YYYY-MM-DD
        dateFormat: true
        timeFormat: false
        pickerUtc:  true
        required: true
        hint: The date the member joined. If the date is in the future, the member will not be displayed.
      - label: Title
        name: tagline
        widget: string
        required: false
        hint: An additional "tagline" that will appear below your name in some places. Typically used for titles or professional descriptions.
      - label: Indie Status
        name: indie_status
        widget: string
        required: false
        hint: How long have you been an indie? Most people use a format like "3+ years".
      - label: Previously
        name: previously
        widget: string
        required: false
        hint: If desired, you can list of organizations you previously worked for/with.
      - label: Currently
        name: currently
        widget: string
        required: false
        hint: If desired, you can list of organizations you currently work for/with.
      - label: Twitter
        name: twitter
        widget: string
        required: false
        hint: Your Twitter handle, without the "@" symbol.
        pattern: [ "[A-Za-z0-9-_]+", "Must only contain ASCII letters, numbers, dashes, and underscores" ]
      - label: Web Links
        name: links
        widget: list
        required: false
        fields:
          - label: Title
            name: title
            widget: string
            hint: What should your link be displayed as? Typically, this is the name of the website you are linking to.
          - label: URL
            name: url
            widget: string
            pattern: [ "https?:\\/\\/[a-z0-9-_]+\\.[a-z]{2,}.*", "Should be a website URL" ] # Quick-n-dirty URL regexp
      - label: About
        name: body
        widget: markdown
        required: false
  - name: projects
    label: Projects
    folder: _projects/
    create: true
    editor:
      preview: true
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: project
      - label: UID
        name: name
        widget: string
        required: true
        hint: Internal identifier. Must be composed only of lower-case ASCII letters, numbers, and dashes. Normally you will use the project title as a base, with spaces replaced by dashes.
        pattern: [ "[a-z0-9-]+", "Must be composed only of lower-case ASCII letters, numbers, and dashes" ]
      - label: Name
        name: title
        widget: string
        required: true
      - label: Tagline
        name: tagline
        widget: string
        required: true
        hint: A "tagline" or "subtitle" the briefly describes your project.
      - label: Published Date
        name: date
        widget: datetime
        format: YYYY-MM-DD
        dateFormat: true
        timeFormat: false
        pickerUtc: true
        required: true
        hint: The date your project will go live. When the date is in the future, the project will be listed as "upcoming".
      - label: Type
        name: type
        widget: select
        options: [ Report ]
        default: [ Report ]
        required: true
      - label: Sequence
        name: sequence
        widget: relation
        collection: sequences
        searchFields: [ title ]
        valueField: name
        displayFields: [ title ]
        required: true
      - label: Hero Image
        name: hero_image
        widget: image
        required: true
        hint: An image file that will be used as the "banner" for your report. Should be either an SVG file, or a JPEG or PNG image at least 1280x800 pixels in size. Text will be displayed over this, so don't use something with a lot of detail (very dark images will also need to use additional CSS to improve page readability).
      - label: Accent Color
        name: accent_color
        widget: string
        default: "200,100,200"
        required: true
        hint: The (comma-separated) RGB color to use as the accent on your report for the projects list page. Should be chosen to go well with your hero image.
        pattern: [ "[0-9]{1,3},[0-9]{1,3},[0-9]{1,3}", "Should be a comma-separated RGB color string." ] # Quick-n-dirty RGB regexp; note that this still allows for invalid color value, since each element of the tuple should really only range from 0 - 255
      - label: Page-Specific Headers
        name: page_headers
        widget: text
        required: false
        hint: Additional header elements (such as CSS blocks or JavaScript imports) you want to include for this page. Primarily (but not exclusively) used to help style any HTML you include in the main body of the page. In particular, using the `.hero:before` class will allow you to apply additional/overide stylings for the hero image.
      - label: Project Leads
        name: lead_editors
        widget: relation
        collection: members
        searchFields: [ title ]
        valueField: name
        displayFields: [ title ]
        multiple: true
        required: true
      - label: Collaborators
        name: collaborators
        widget: relation
        collection: members
        searchFields: [ title ]
        valueField: name
        displayFields: [ title ]
        multiple: true
        required: true
      - label: Summary
        name: summary
        widget: markdown
        required: true
        hint: A summary of your project. This will be displayed over your hero image.
      - label: Page Content
        name: body
        widget: markdown
        required: true
  - name: project_pages
    label: Project Pages
    folder: _project_pages/
    create: true
    editor:
      preview: true
    fields:
      - label: UID
        name: name
        widget: string
        required: true
        hint: Internal identifier. Must be composed only of lower-case ASCII letters, numbers, and dashes. Normally you will use the project title as a base, with spaces replaced by dashes.
        pattern: [ "[a-z0-9-]+", "Must be composed only of lower-case ASCII letters, numbers, and dashes" ]
      - label: Name
        name: title
        widget: string
        required: true
      - label: Project
        name: project
        widget: relation
        collection: projects
        searchFields: [ title ]
        valueField: name
        displayFields: [ title ]
        multiple: false
        required: true
      - label: Permalink
        name: permalink
        widget: string
        required: true
        hint: Where the page should appear on the site. Should be "/projects/PROJECT-NAME/PAGE-NAME/".
        pattern: [ "/projects/[a-z0-9-]+/[a-z0-9-]+/", "Must be composed of three sections, the first of which is 'projects', the second of which is the associated project name, and the third of which is the UID set above, with leading/trailing, and separating '/' characters" ]
      - label: Original Link
        name: original_link
        widget: string
        required: false
        hint: If the link on the corresponding project's page should point off-site, include the URL here.
        pattern: [ "https?:\\/\\/[a-z0-9-_]+\\.[a-z]{2,}.*", "Should be a website URL" ] # Quick-n-dirty URL regexp
      - label: Published Date
        name: date
        widget: datetime
        format: YYYY-MM-DD
        dateFormat: true
        timeFormat: false
        pickerUtc: true
        required: true
        hint: The date the project page will go live. When the date is in the future, page will not be generated.
      - label: Page Author
        name: author
        widget: relation
        collection: members
        searchFields: [ title ]
        valueField: name
        displayFields: [ title ]
        multiple: false
        required: true
      - label: Hero Image
        name: hero_image
        widget: image
        required: true
        hint: An image file that will be used to represent the page in the corresponding project's page. Should ideally be either an SVG file, or a JPEG or PNG image at least 1280x800 pixels in size. Be aware that the image will be cropped to (almost) a square in many cases, so all of the important parts should be in the central 800x800 region.
      - label: Page-Specific Headers
        name: page_headers
        widget: text
        required: false
        hint: Additional header elements (such as CSS blocks or JavaScript imports) you want to include for this page. Primarily (but not exclusively) used to help style any HTML you include in the main body of the page.
      - label: Description
        name: description
        widget: text
        required: true
        hint: A short one-to-two sentence description of the page, to be displayed on the corresponding project's page.
      - label: Display in Project
        name: display
        widget: boolean
        default: true
        hint: If "true", this page will be displayed on the corresponding project's page. If "false", it will not be displayed (but will still be generated). Setting to false is useful when creating reference pages and appendices.
      - label: Page Content
        name: body
        widget: markdown
        required: true
  - label: Sequences
    name: sequences
    folder: _sequences/
    create: true
    editor:
      preview: false
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: project-list
      - label: UID
        name: name
        widget: string
        required: true
        hint: Internal identifier. Must be composed only of lower-case ASCII letters, numbers, and dashes. Normally you will use the sequence name as a base, with spaces replaced by dashes.
        pattern: [ "[a-z0-9-]+", "Must be composed only of lower-case ASCII letters, numbers, and dashes" ]
      - label: Name
        name: title
        widget: string
        required: true
      - label: Start Date
        name: date
        widget: datetime
        format: YYYY-MM-DD
        dateFormat: true
        timeFormat: false
        pickerUtc: true
        required: true
      - label: Counting Phrase
        name: count_phrase
        widget: string
        required: false
        hint: The phrase to use after the day count from the sequence start. For example, the COVID-19 sequence uses "Pandemic Mean Time".
      - label: Sequence Description
        name: body
        widget: hidden
        default: ""
  - label: "Slogans & Tips"
    name: slogans-and-tips
    editor:
      preview: false
    files:
      - label: Slogans
        name: slogans
        file: _data/slogans.yml
        fields:
          - label: Slogans
            name: slogans
            widget: list
            collapsed: false
            fields:
              - label: Slogan
                name: slogan
                widget: string
                required: true
                hint: Text only; no markdown or HTML.
      - label: Tips
        name: tips
        file: _data/tips.yml
        fields:
          - label: Tips
            name: tips
            widget: list
            collapsed: false
            fields:
              - label: Tip
                name: tip
                widget: string
                required: true
                hint: Text only; no markdown or HTML.
              - label: Author
                name: author
                widget: relation
                collection: members
                searchFields: [ title ]
                valueField: name
                displayFields: [ title ]
                multiple: false
                required: true
                hint: Tip author (must be a Yak Collective member).
  - label: Pages
    name: pages
    editor:
      preview: true
    files: 
      - label: Home
        name: home-page
        file: index.md
        fields:
          - label: Layout
            name: layout
            widget: hidden
            default: minimal
          - label: Page-Specific Headers
            name: page_headers
            widget: text
            required: false
            hint: Additional header elements (such as CSS blocks or JavaScript imports) you want to include for this page. Primarily (but not exclusively) used to help style any HTML you include in the main body of the page.
          - label: Content
            name: body
            widget: markdown
            required: true
      - label: About
        name: about-page
        file: about.md
        fields:
          - label: Layout
            name: layout
            widget: hidden
            default: page
          - label: Title
            name: title
            widget: string
            required: true
          - label: Page-Specific Headers
            name: page_headers
            widget: text
            required: false
            hint: Additional header elements (such as CSS blocks or JavaScript imports) you want to include for this page. Primarily (but not exclusively) used to help style any HTML you include in the main body of the page.
          - label: Content
            name: body
            widget: markdown
            required: true
