name: Build and Deploy knack-migrations

on:
   workflow_dispatch:

jobs:
  build:
    # 2. Using the latest Ubuntu image
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2 #orig had #1, but we need to run on branch
        with:
   #needs to be name of branch we run on. 
         ref: knack-migration

      # 3. https://github.com/actions/setup-node#usage
      #- uses: actions/setup-node@v1
      #  with:
      #    node-version: "12.x"
      #- run: npm install
      # This triggers `build` script in "package.json" #we hope...
      #- run: npm run build
      # 4. Deploy the  build to Netlify
      #- uses: netlify/actions/cli@master
      #  env:
      #    NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #    NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_COMPETENT_SHOCKLEY_33F53C }}
      #  with:
      #    # 5. "build" creates "public" folder, which is what we are deploying #hope this works. or is it even needed?
      #    args: deploy --dir=public --prod
      #    secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
      #    

      - name: try buildmaster
        uses: "netlify/actions/build@master"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_COMPETENT_SHOCKLEY_33F53C }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        #secrets: ["GITHUB_TOKEN", "NETLIFY_SITE_ID"]
