name: Site update automation

on:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  site-update-automation:
    name: Site update automation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download dependencies
        run: |
          sudo apt install nkf
      - name: Pull RSS feeds
        env:
          KNACK_APP_ID: ${{ secrets.KNACK_APP_ID }}
          KNACK_API_KEY: ${{ secrets.KNACK_API_KEY }}
          KNACK_OBJECT: ${{ secrets.KNACK_OBJECT }}
        run: |
          ./_bin/rss-pull-feeds.sh
      - name: Push oldest queued post to Discord
        env:
          DISCORD_CHANNEL_URL: ${{ secrets.DISCORD_WEBHOOK_YAKS_AT_WORK }}
        run: |
          ./_bin/push-to-discord.sh
      - name: Commit changes to repository
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A -v
          git commit -m "Pushed oldest queued tweet to Twitter" || true
          git push
      - name: Push health stats to Discord
        env:
          DISCORD_CHANNEL_URL: ${{ secrets.DISCORD_WEBHOOK_WEBSITE_HEALTH }}
          GH_ACCOUNT_SLUG: ${{ secrets.GH_ACCOUNT_SLUG }}
          GH_TOKEN: ${{ secrets.GH_ROBOT_ACCESS_TOKEN }}
          NETLIFY_ACCOUNT_EMAIL: ${{ secrets.NETLIFY_ACCOUNT_EMAIL }}
          NETLIFY_ACCOUNT_SLUG: ${{ secrets.NETLIFY_ACCOUNT_SLUG }}
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
        run: |
          GITHUB_DATA="$(curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GH_ACCESS_TOKEN"  https://api.github.com/orgs/${GH_ACCOUNT_SLUG}/settings/billing/actions)"

          curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"GitHub Workflow Minutes: $(echo $GITHUB_DATA | jq .total_minutes_used) / $(echo $GITHUB_DATA | jq .included_minutes)\"}" "$DISCORD_CHANNEL_URL"

          NETLIFY_DATA="$(curl -H "User-Agent: MyApp $NETLIFY_ACCOUNT_EMAIL" -H "Authorization: Bearer $NETLIFY_TOKEN" https://api.netlify.com/api/v1/${NETLIFY_ACCOUNT_SLUG}/builds/status)"

          curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"Netlify Build Minutes: $(echo $NETLIFY_DATA | jq .minutes.current) / $(echo $NETLIFY_DATA | jq .minutes.included_minutes)\"}" "$DISCORD_CHANNEL_URL"
